export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";

export const REQUEST_CONTACTS = "REQUEST_CONTACTS";
export const GOT_CONTACTS = "GOT_CONTACTS";
export const DIDNOT_GET_CONTACTS = "DIDNOT_GET_CONTACTS";

export const POST_CONTACTS_REQUEST = "POST_CONTACTS_REQUEST";
export const POST_CONTACTS_SUCCESS = "POST_CONTACTS_SUCCESS";
export const POST_CONTACTS_FAIL = "POST_CONTACTS_FAIL";

export const EDIT_CONTACT_REQUEST = "EDIT_CONTACT_REQUEST";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_FAIL = "EDIT_CONTACT_FAIL";

export const DELETE_CONTACTS_REQUEST = "DELETE_CONTACTS_REQUEST";
export const DELETE_CONTACTS_SUCCESS = "DELETE_CONTACTS_SUCCESS";
export const DELETE_CONTACTS_FAIL = "DELETE_CONTACTS_FAIL";
